//! Command-line definition for the `ow` binary.
//!
//! This module is deliberately thin: it owns the [`clap`] surface (the
//! [`Args`] struct, the [`Commands`] enum, the [`Cli`] entry) and the single
//! piece of pure derivation logic that turns parsed flags into a
//! [`WakeRequest`]. All side effects — tracing setup, daemon spawning, output —
//! live in [`crate::main`] / `main.rs`, not here.
//!
//! Design notes:
//!
//! - `ow` with no subcommand prints status (same as `ow status`); `clap` is
//!   told the subcommand is optional and `main.rs` fills in the default.
//! - `--json` and `-v`/`--verbose` are global flags so they apply regardless of
//!   which subcommand was used. `--json` only has an observable effect on the
//!   commands that produce structured output (`status`, `doctor`); for the
//!   others it is accepted and ignored.
//! - The hidden `__daemon` subcommand is how `ensure_started` re-execs the
//!   binary into the daemon process. It is marked `hide = true` so it never
//!   appears in `--help`, matching the contract in `daemon::DAEMON_SUBCOMMAND`.

use clap::{Parser, Subcommand};

use crate::model::{WakeRequest, WakeTarget};

/// Top-level `ow` invocation.
///
/// `clap` parses into this; [`Cli::command`] (generated by the derive) drives
/// `--help`, and the optional `command` field is what `main.rs` dispatches on.
/// When `command` is `None` the CLI behaves as `ow status`.
#[derive(Debug, Parser)]
#[command(
    name = "ow",
    bin_name = "ow",
    version,
    about = "Oxiwake — keep your machine awake where the OS allows it, and tell you when it cannot.",
    long_about = "Oxiwake holds a wake lock open for as long as you ask, and reports honestly \
                  when the OS will not let it. Think of it as caffeinate / systemd-inhibit, \
                  cross-platform, with a daemon you can toggle on and off."
)]
pub struct Cli {
    /// Emit machine-readable JSON for commands that produce structured output
    /// (`status`, `doctor`). Accepted globally; ignored by commands that have
    /// no structured form.
    #[arg(short, long, global = true)]
    pub json: bool,

    /// Increase verbosity (repeat for more detail). Raises the `tracing` level
    /// past whatever `RUST_LOG` requests.
    #[arg(short = 'v', long, global = true, action = clap::ArgAction::Count)]
    pub verbose: u8,

    /// The subcommand to run. When omitted, `ow` behaves as `ow status`.
    #[command(subcommand)]
    pub command: Option<Commands>,
}

/// The user-facing verbs.
///
/// Each variant corresponds to one row of the v0.1 scope in `docs/setup.md`.
/// `Daemon` is the hidden internal entry point used by `ensure_started`; it is
/// excluded from help via `#[command(hide = true)]`.
#[derive(Debug, Clone, Subcommand)]
pub enum Commands {
    /// Start the keep-awake daemon (idempotent: a no-op if already running).
    On {
        /// Additionally keep the display on where the backend supports it.
        #[arg(long)]
        display: bool,
        /// Be aggressive about lid-close handling (adds `handle-lid-switch`;
        /// often needs privilege).
        #[arg(long)]
        aggressive_lid: bool,
        /// Human-readable reason handed to the OS (shown by
        /// `systemd-inhibit --list`, etc.).
        #[arg(long, value_name = "TEXT")]
        reason: Option<String>,
    },

    /// Stop the keep-awake daemon (idempotent: a no-op if not running).
    Off,

    /// Start the daemon if it is off, or stop it if it is on.
    Toggle {
        /// Additionally keep the display on (forwarded to `ow on` when
        /// starting).
        #[arg(long)]
        display: bool,
        /// Be aggressive about lid-close handling (forwarded to `ow on`).
        #[arg(long)]
        aggressive_lid: bool,
        /// Human-readable reason handed to the OS (forwarded to `ow on`).
        #[arg(long, value_name = "TEXT")]
        reason: Option<String>,
    },

    /// Print the current lock state.
    Status,

    /// Probe the environment and every compiled-in backend, and print a report.
    Doctor,

    /// Hidden internal entry point: run the daemon process.
    ///
    /// Spawned (detached) by [`daemon::ensure_started`](crate::daemon). Never
    /// invoked directly by a user, and hidden from `--help`.
    #[command(name = "__daemon", hide = true)]
    Daemon,
}

/// Flags that can shape a [`WakeRequest`] — shared by `on` and `toggle`.
///
/// Extracted into a struct so the request-building logic in [`build_request`]
/// has a single, named input regardless of which verb carried the flags.
#[derive(Debug, Clone, Default)]
pub struct RequestFlags {
    /// Keep the display on where supported.
    pub display: bool,
    /// Add aggressive lid-close handling.
    pub aggressive_lid: bool,
    /// Override the default OS-facing reason string.
    pub reason: Option<String>,
}

impl RequestFlags {
    /// Collect the request-shaping flags from the `On` variant.
    pub fn from_on(display: bool, aggressive_lid: bool, reason: Option<String>) -> Self {
        RequestFlags {
            display,
            aggressive_lid,
            reason,
        }
    }

    /// Collect the request-shaping flags from the `Toggle` variant.
    pub fn from_toggle(display: bool, aggressive_lid: bool, reason: Option<String>) -> Self {
        // Same fields, same meaning; the separate constructor just documents
        // which call site the flags came from.
        RequestFlags {
            display,
            aggressive_lid,
            reason,
        }
    }
}

/// Build a [`WakeRequest`] from parsed flags, starting from the platform
/// default and layering the user's choices on top.
///
/// The platform default is [`WakeRequest::default_linux`] on Linux and
/// [`WakeRequest::default_windows`] on Windows. When `--aggressive-lid` is set,
/// [`WakeTarget::LidSwitch`] is added to the target set (de-duplicated) so the
/// request faithfully reflects the user's intent regardless of which backend
/// ends up honoring it.
///
/// This is a pure function — the only clock read (`started_unix`) happens in
/// `main.rs`, not here.
pub fn build_request(flags: &RequestFlags) -> WakeRequest {
    // Start from the platform-appropriate good default.
    #[cfg(target_os = "linux")]
    let mut req = WakeRequest::default_linux();
    #[cfg(windows)]
    let mut req = WakeRequest::default_windows();
    #[cfg(not(any(target_os = "linux", windows)))]
    let mut req = WakeRequest::default_linux();

    req.display = flags.display;
    req.aggressive_lid = flags.aggressive_lid;

    if flags.aggressive_lid {
        // De-duplicate: only add LidSwitch if it is not already requested.
        if !req.targets.contains(&WakeTarget::LidSwitch) {
            req.targets.push(WakeTarget::LidSwitch);
        }
    }

    if let Some(reason) = &flags.reason {
        if !reason.trim().is_empty() {
            req.reason = reason.clone();
        }
    }

    req
}

/// The clap-derived top-level entry, kept as a function so `main.rs` can ask
/// for a freshly-built [`Cli`] from `env::args` without reaching into clap's
/// `Parser` trait directly.
///
/// Equivalent to `Cli::parse()`; provided as a named seam for readability and
/// for ease of swapping in `try_parse` / custom args in tests.
pub fn parse() -> Cli {
    Cli::parse()
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::WakeTarget;

    #[test]
    fn build_request_applies_display_and_reason() {
        let flags = RequestFlags {
            display: true,
            aggressive_lid: false,
            reason: Some("compiling".to_string()),
        };
        let req = build_request(&flags);
        assert!(req.display);
        assert!(!req.aggressive_lid);
        assert_eq!(req.reason, "compiling");
        // The lid target must not have been added when aggressive_lid is off.
        assert!(!req.targets.contains(&WakeTarget::LidSwitch));
    }

    #[test]
    fn build_request_adds_lid_switch_when_aggressive() {
        let flags = RequestFlags {
            display: false,
            aggressive_lid: true,
            reason: None,
        };
        let req = build_request(&flags);
        assert!(req.targets.contains(&WakeTarget::LidSwitch));
    }

    #[test]
    fn build_request_blank_reason_is_ignored() {
        let flags = RequestFlags {
            display: false,
            aggressive_lid: false,
            reason: Some("   ".to_string()),
        };
        let req = build_request(&flags);
        // A whitespace-only reason must not clobber the default.
        assert!(!req.reason.trim().is_empty());
    }

    #[test]
    fn build_request_defaults_when_empty() {
        let req = build_request(&RequestFlags::default());
        // The platform default carries at least one target.
        assert!(!req.targets.is_empty());
    }
}
